### ISSUE TITLE
Enable/Disable Plugin via checkbox

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/GitExtensions.GerritPlugin#28]
As a user I want an additional setting to enable or disable this plugin, so that I can decide if I want to use the delivered features or not.

**Comment by maraf** [comment]
The way to accomplish this is through `GitPluginBase.GetSettings`, [example there](https://github.com/maraf/GitExtensions.BundleBackuper/blob/b1971e0a51cdc3a8038ed68e9dc5c961ad86486b/src/GitExtensions.BundleBackuper/Plugin.cs#L53).
