### ISSUE TITLE
Extensions 3.5 not working with gerrit plugin

### ISSUE THREAD

**Issue by MASDias** [gitextensions/GitExtensions.GerritPlugin#33]
## Current behaviour

As of the last update, from 3.4 to 3.5 the the gerrit plugin does not start, i always get the following error as pop up:

**reference object not set to an instance of a object**

## Steps to reproduce

Need the gerrit plugin and gerrit review file

**Comment by gerhardol** [comment]
Moving to the Gerrit plugin repo, not part of the main app

**Comment by pmiossec** [comment]
Did you updated the Gerrit plug-in? Because it seems that the v1.1 has
released tu support v3.5 of GitExtensions...

**Comment by mast-eu** [comment]
This error appears when using Git Extensions v.3.5 in combination with Gerrit Plugin 1.0.0.

Please use `Plugins > Plugin Manager` and update Gerrit Plugin.
