### ISSUE TITLE
Missing Gerrit Plugin in GitExtension since V2

### ISSUE THREAD

**Issue by 011V32** [gitextensions/GitExtensions.GerritPlugin#52]
### Environment

- Gerrit Plugin 2.0.0.125 and 2.0.1.128
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4420.0
- DPI 168dpi (175% scaling)

### Issue description

The plugin is installed and listed in the plugin manager, but the plugin is not listed under plugins, also the green buttons are missed and the settings for the gerrit plugin under "Tools" -> "Settings" -> "Plugins" -> "Gerrit Code Review" is also not available since V2.0.0.
Probably because I use .Net 4?

### Steps to reproduce

Only Install the Plugin in the actual GitExtensions version (probably without .Net 5).

### Expected behavior

Function working plugin or at least an information, that additional updates are required.

### Actual behavior

The GerritPlugin is installed, but not functional.

**Comment by 011V32** [comment]
I just realized that I missed the information that V2 is compatible with GitExtensions 4.
Is it intentional that this version can then be installed on older versions?

**Comment by pmiossec** [comment]
From what I could see here: https://github.com/gitextensions/GitExtensions.GerritPlugin/releases

v >= 2.0 are for the not yet released next version of GitExtensions (that will use .net >= 5 )
The last version available for current v3.5.4 of GitExtensions (that use .net 4) is [1.3.2](https://github.com/gitextensions/GitExtensions.GerritPlugin/releases/tag/v1.3.2)

**Comment by 011V32** [comment]
As I said above, I am aware of this. But from my point of view this is still an error, since these versions are the current versions to be installed, but they do not work together and there is no error or information is displayed when selecting the plugin in GitExtension.

**Comment by RussKie** [comment]
What behaviour do you expect?

**Comment by 011V32** [comment]
Ideally, a plugin that is not compatible cannot be installed at all.
If this is not easily possible, at least some information should be displayed on the installation page.
THX

**Comment by lekhmanrus** [comment]
[Compatibility Matrix](https://github.com/gitextensions/GitExtensions.GerritPlugin#compatibility-matrix) was added to the readme.
