### ISSUE TITLE
Use branch from .gitreview as target branch

### ISSUE THREAD

**Issue by eladavron** [gitextensions/GitExtensions.GerritPlugin#53]
### Feature description

Allow the target branch name to be taken from .gitreview instead of the local branch name
(obviously for people who prefer the current behavior, this should be optional).

### Use case

In much older versions of the plugin, the target branch when uploading was the branch specified in .gitreview as "default branch".
This helped our users use whatever local branch name they wanted (since they often have different changes on the same branch) and always upload it to the correct target branch.
(Now the behavior is that it uses the same name as the local branch)

**Comment by lekhmanrus** [comment]
Yep, that's a good idea to move that to plugin settings and give the user the ability to change this behavior. Thanks!

**Comment by tank09** [comment]
Hi, is there any progress to control this via the plugin settings ?
Is there someone working on it ?

**Comment by tank09** [comment]
Hi, is there any progress to control this via the plugin settings ?
Is there someone working on it ?

**Comment by lekhmanrus** [comment]
Hi @tank09, I would say one-two week (most likely - less). 🙂

**Comment by lekhmanrus** [comment]
Now available in GitExtensions.GerritPlugin v2.0.4.

**Comment by tank09** [comment]
Many thanks.
