### ISSUE TITLE
Method not found 'Boolean GitCommands.GitSshHelpers.Plink()' after update to GE 4.0.1

### ISSUE THREAD

**Issue by mycroes** [gitextensions/GitExtensions.GerritPlugin#55]
### Environment

Gerrit plugin version: 2.0.1
Git Extensions 4.0.1.15887
Build https://github.com/gitextensions/gitextensions/commit/f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
Git 2.38.1.windows.1
Microsoft Windows NT 10.0.19045.0
.NET 6.0.12

### Issue description

On publish, the following exception dialog appears:
![image](https://user-images.githubusercontent.com/122017/207867380-8566efc4-a24a-4aaf-a30c-823f1067a65c.png)

### Steps to reproduce

1. Open publish dialog
2. Press publish

### Expected behavior

Publish resumes as usual

### Actual behavior

Exception is thrown, publish doesn't work.

### Did this work in previous version of Gerrit plugin?

Worked in previous version of GE; 4.0.0.

**Comment by RussKie** [comment]
The plugin has to be updated and a new version needs to be published.

**Comment by mycroes** [comment]
> The plugin has to be updated and a new version needs to be published.

Shame that this breaks on a minor version increment. I'm guessing it's not considered public API though...

**Comment by RussKie** [comment]
There's no established mechanism to track the public API surface. It's
something we planned to do, but it's on the backlog.

The external plugins are on a periphery for the core team.

**Comment by pirluq** [comment]
Hello, any reason 2.0.2 is not available on nuget.org yet?
I can't build the project locally due to corporate firewall.

Regards

**Comment by lekhmanrus** [comment]
Hi @RussKie, Could you please trigger a build on AppVeyor again if that is possible, so it automatically deploys the new version to NuGet? Thanks! 🙂

**Comment by pmiossec** [comment]
> Hi @RussKie, Could you please trigger a build on AppVeyor again if that is possible, so it automatically deploys the new version to NuGet? Thanks! 🙂

Which build?
I tried to have a look but I didn't found what is the process to release a new version.
maybe adding some lines in the README could be good...

**Comment by pmiossec** [comment]
i launched one from 'master' and one from the tag without success
https://ci.appveyor.com/project/gitextensions/gitextensions-gerritplugin/history

I had the messenge: "NuGet" deployment for branch "master" has been skipped because current branch is "v2.0.2"

Or
"NuGet" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
Build success

**Comment by lekhmanrus** [comment]
@pmiossec, tbh - I do not remember how release workflow works) I believe a new commit to the master branch should trigger the automatic build and deployment of the new version to NuGet.

**Comment by RussKie** [comment]
We can't currently upload the new package to our NuGet account, because NuGet now requires us to sign the package which we can't do.

**Comment by pmiossec** [comment]
> We can't currently upload the new package to our NuGet account, because NuGet now requires us to sign the package which we can't do.

Is it a new requirement? I have uploaded a package last week (but not in GE nuget account) and it worked...

**Comment by RussKie** [comment]
They forced me to register the signing key to upload the PM because it's
signed. Now I'm unable to upload unsigned packages.

This wasn't enforced until recently.

**Comment by lekhmanrus** [comment]
Hi @RussKie, could you please provide a certificate so I can sign the Gerrit plugin and upload it to NuGet? And what is the new workflow for deployment should we have now? do we use [SignPath](https://about.signpath.io/)? Thanks!

**Comment by RussKie** [comment]
Yes, we use SignPath. But we have limits how many projects we can sign.

I've got a response from NuGet folks how to upload an unsigned package.
I'm currently away so it may be some time before I can enact that.

**Comment by RussKie** [comment]
The new package has been published: https://www.nuget.org/packages/GitExtensions.GerritPlugin/2.0.2.152
