### ISSUE TITLE
Wrong compatibility of version 2.0.3 in the compatibility matrix in the readme

### ISSUE THREAD

**Issue by 011V32** [gitextensions/GitExtensions.GerritPlugin#64]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 168dpi (175% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The compatibility of version 2.0.3 is wrong in the [Compatibility Matrix](https://github.com/gitextensions/GitExtensions.GerritPlugin#compatibility-matrix) in the readme.
There it says that 2.0.3 could be used with Git Extensions version >= 4.0.1, but in the [release notes](https://github.com/gitextensions/GitExtensions.GerritPlugin/releases/tag/v2.0.3) it states that is is compatible with Git Extensions version 4.1.0.

### Steps to reproduce

Look at [Compatibility Matrix](https://github.com/gitextensions/GitExtensions.GerritPlugin#compatibility-matrix) and [release notes](https://github.com/gitextensions/GitExtensions.GerritPlugin/releases/tag/v2.0.3)

### Expected behavior

<html><body>

Git Extensions | Gerrit Plugin
-- | --
v <= 3.5.x | v <= 1.3.2
3.5.x < v <= 4.0.0 | 2.0.0 <= v <= 2.0.1
4.0.1 <= v < 4.1.0 | v == 2.0.2
4.1.0 <= v | 2.0.3 <= v

</body>
</html>

### Actual behavior

<html><body>

Git Extensions | Gerrit Plugin
-- | --
v <= 3.5.x | v <= 1.3.2
3.5.x < v <= 4.0.0 | 2.0.0 <= v <= 2.0.1
4.0.1 <= v | 2.0.2 <= v

</body>
</html>

**Comment by lekhmanrus** [comment]
Thanks @011V32!
