### ISSUE TITLE
Can install but can't use/see plugin v 2.0.3.158 under GitExtension 4.0.2

### ISSUE THREAD

**Issue by dfev77** [gitextensions/GitExtensions.GerritPlugin#65]
### Environment

- Gerrit plugin version: 2.0.3.158
- Git Extensions 4.0.2.15956
- Build 14d332665cb796754be2ae0f20af76778a58f887
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions
```
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I tried an unofficial GitEx build version cause Plugin Manager would not appear under GitExt
Installed  Gerrit plugin version: 2.0.3.158 but I cannot see it under plugins nor does it show in toolbar

### Steps to reproduce

- Get GitExt standalone from from https://ci.appveyor.com/api/buildjobs/4lrefbxmky8u3ee1/artifacts/combined.4.0.2.15956-unsigned.zip (see https://github.com/gitextensions/gitextensions/issues/8794)
- Install gerrit plugin 2.0.3.158 (latest right now)

### Expected behavior

I can use it :)

### Actual behavior

Plugin does not show in GitExt

**Comment by lekhmanrus** [comment]
Hi @dfev77, please try using Gerrit plugin v2.0.2 for GitExtensions 4.0.1 <= v < 4.1.0. Or use GitExtensions >= v4.1.0 with Gerrit v2.0.3. Please take a look [Compatibility Version Matrix](https://github.com/gitextensions/GitExtensions.GerritPlugin#compatibility-version-matrix).
Please let me know if you still have any issues there.

**Comment by maraf** [comment]
The problem with 2.0.2 is that it has wrong version on dependency on GitExtensions.Extensibility

![image](https://user-images.githubusercontent.com/10020471/212494704-24023ed6-2f54-4827-9048-4bb4db6ed7f4.png)

In general, I don't think that it is ideal to increment only patch number in version when target/required version of Git Extensions changes. In my plugins, I always increment major. I basically follow semantic versioning. It leaves options when patch for older version is needed.

**Comment by dfev77** [comment]
So, 2.0.2.152 cannot be installed through the PluginManager GUI (not listed)
If I manually install it (copy dll from nuget package into `UserPlugins\GitExtensions.GerritPlugin\` and update `UserPlugins\packages.config` ) is listed in manager as `Not compatible`, and also does not seem to be loaded.

Now, as 4.0.1/4.0.2 is the current official release and it will take some time to have 4.1.0 release AND there is not Gerrit plugin available that is compatible for this version, is there a plan to allow users to use this plugin with current official GExt version? (beside DIY 😄 )

**Comment by maraf** [comment]
I believe that targeting Git Extensions 4.1 at this moment is not a good strategy, as nobody knowns if the plugin will be compatible with whatever changes may come in 4.1 release. (As we don't have a stable API yet, most of the plugins rely on API that may be changed). 

So from my point of view, it would be ideal to release Gerrit plugin 2.0.4 targeting Git Extensions 4.0.1/2 and when Git Extensions 4.1 will be released, produce a Gerrit plugin 3.0.0. 

I have summarized some of the good practices for authoring plugins here https://github.com/gitextensions/gitextensions.plugintemplate#good-practices

cc @lekhmanrus

**Comment by lekhmanrus** [comment]
Please use GitExtensions.GerritPlugin v2.0.4 for GitExtensions v >= 4.0.1.

**Comment by maraf** [comment]
@dfev77 The published Git Extensions 4.0.2 is [4.0.2.16100](https://github.com/gitextensions/gitextensions/releases/tag/v4.0.2). I have tested with that version (portable) and the Gerrit plugin 2.0.4.177 works. Can you update the Git Extensions? I guess that Git Extensions 4.0.2.15956 is a nightly build.

**Comment by dfev77** [comment]
Thanks @maraf, it works with that version.

**Comment by dfev77** [comment]
Thanks @maraf, it works with that version.
