### ISSUE TITLE
Improvement of Gerrit plugin - provide hyperlinks to new patchsets of existing change in Gerrit

### ISSUE THREAD

**Issue by litmanovich** [gitextensions/GitExtensions.GerritPlugin#7]
When publishing the first commit the plugin opens a window with a link to the submitted change in Gerrit, which is very convenient. However when publishing additional patchsets to the Gerrit there is no such window. It'd be very useful to provide a hyperlink to all the additional patchsets similar to the first one.

Thanks in advance,
Igor.

**Comment by thimmy687** [comment]
Hey guys,

I like this request and I'd would implement this like this:

![image](https://user-images.githubusercontent.com/7715216/111916804-0850f300-8a7d-11eb-9294-911861ec0530.png)

Can somebody give me a hint how I need to do this?

Is it related to this implementation:

https://github.com/gitextensions/gitextensions/blob/24ed8db092c93d94ce0f0d4183273f205d157a5a/GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/GitHubExternalLinkDefinitionExtractor.cs

I already know, that I will need this here somehow :)

**Comment by gerhardol** [comment]
The related links are currently only inserted by Revision Links:
https://git-extensions-documentation.readthedocs.io/en/release-3.4/settings.html#git-extensions-revision-links

Can such rules be added?

**Comment by thimmy687** [comment]
thanks for the hint :)

I will check this

**Comment by thimmy687** [comment]
oh yes it works, but I need to find the right config 

here is the id missing:
![image](https://user-images.githubusercontent.com/7715216/111918131-ef980b80-8a83-11eb-8646-f4de68eb55af.png)

![image](https://user-images.githubusercontent.com/7715216/111918148-03dc0880-8a84-11eb-95e3-d43647714369.png)

and here is "Change" and "ID" also attached :/

![image](https://user-images.githubusercontent.com/7715216/111918302-bdd37480-8a84-11eb-9d32-9c574ebff2d5.png)


![image](https://user-images.githubusercontent.com/7715216/111918245-7d73f680-8a84-11eb-8a45-878231acc76c.png)

**Comment by thimmy687** [comment]
Now it works :)

![image](https://user-images.githubusercontent.com/7715216/111919306-a054d980-8a89-11eb-9d8f-46a7a403730c.png)

(Change-Id: )#?I\w+
I\w{2,}

Patchset | https://gerrit-review.googlesource.com/q/{0}

**Comment by thimmy687** [comment]
Is it possible to deliver such Revision link with or set them by the plugin?

I can't tell all of our users to do this setting by hand :/

**Comment by gerhardol** [comment]
You can set this in the repo with a GitExtensions.settings file - see GE repo itself for an example
I use this at work for BitBucket and Jira links
(there are quite some updates for do for me when adding a new feature, Jenkins server or naming is changed etc...)

**Comment by RussKie** [comment]
This looks like achieable without changes to the app.
If you use Twitter you can post the solution there, tagging @git_extensions
and we'll retweet it.
