### ISSUE TITLE
Adapt namespace of OsShellUtil to GE 4.2

### ISSUE THREAD

**Issue by mstv** [gitextensions/GitExtensions.GerritPlugin#77]
### Feature description

https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/78

**Comment by lekhmanrus** [comment]
It was fixed in https://github.com/gitextensions/GitExtensions.GerritPlugin/pull/74. Waiting for review https://github.com/gitextensions/GitExtensions.GerritPlugin/pull/76  to release new version.
