### ISSUE TITLE
Plugin doesn't load after update to GitExtensions 5.0.0

### ISSUE THREAD

**Issue by mycroes** [gitextensions/GitExtensions.GerritPlugin#86]
### Environment

- Gerrit plugin version: 2.0.8.209
- Git Extensions version: 5.0.0.17897
- GIT version: 2.42.0.windows.2
- OS version: Windows 10.0.19045.0
- .NET version: 8.0.8

### Issue description

After updating GitExtensions to v5, the Gerrit plugin no longer seems to load (which makes sense due to the changed plugin interfaces).

### Steps to reproduce

- Install GitExtensions v5
- Install Gerrit plugin

### Expected behavior

Gerrit plugin publish and fetch buttons show in the toolbar

### Actual behavior

No sign of the Gerrit plugin

### Did this work in previous version of Gerrit plugin?

Probably not, but it did work in previous version of GitExtensions.

**Comment by RussKie** [comment]
The plugin needs to be updated for v5.

**Comment by pmiossec** [comment]
PR #87 attempt to fix the issue.

A dev version of the plugin could be tested here: https://ci.appveyor.com/project/gitextensions/gitextensions-gerritplugin/builds/50581914/artifacts

You could test it and report if it is working.
Maybe it will speed up the process.

But as I don't use Gerrit, I don't think I will continue my effort further. (Maybe @lekhmanrus ?)

**Comment by lekhmanrus** [comment]
Hi @pmiossec, It looks like it is working fine! Thank you! 😊
